version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:

  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
            - packaje.json

  semver:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: semantic version
          command: npm run semantic-release
          env:
            GITHUB_TOKEN: ${GH_TOKEN}
            NPM_TOKEN: ${NPM_TOKEN}
            CI: true

workflows:
  build:
    jobs:
      - build-and-test
      - semver:
          requires:
            - build-and-test
